- hosts: all
  tasks:
      - name: python packages
        apt: pkg={{ item }} state=latest
        with_items:
            - python-beautifulsoup
            - python-lxml
            - python-matplotlib
            - python-numpy
            - python-pandas
            - python-scipy
            - python-sqlalchemy
            - python-sqlite
            - python-tornado
            - python-virtualenv
            - python-zmq
            - python-pytest
            # Other packages that may interest you...
            # - cython
            # - python-mvpa
            # - python-mvpa-lib
            # - python-rpy
            # - python-xlrd
            # - python-xlwt

      - pip: name=ipython version=1.1
      - pip: name=vincent

      # It might be nice to install a newer version of requests as well,
      # installed packages cloud-init and ssh-import-id depend on it, but I
      # guess once I'm init'd, these can be removed?

      - name: Useful packages for data science and computation
        apt: pkg={{ item }} state=latest
        with_items:
            # This should automatically set up openBLAS for runtime stuff, but
            # won't necessarily help with code you compile
            - libopenblas-base
            - git

# TODO - set up user's ssh keys, perhaps also git identity? This could also be
# done in an interactive setup script...
